# .github/workflows/ci.yml
name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Step 2: Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            # Step 3: Install dependencies
            - name: Install dependencies
              run: npm install

            # Step 4: Compile TypeScript to JavaScript
            - name: Compile TypeScript
              run: npm run build

            # Step 5: Run Tests
            - name: Run Tests
              run: |
                  npm run start & # Start the dev server in the background
                  sleep 5 # Allow some time for the server to start
                  node ./dist/NodeJsSecurify.js

            # Step 6: Check for Linting Issues
            - name: Lint the code
              run: npm run lint

            # Step 7: Ensure that changes are properly formatted (optional)
            - name: Check code formatting
              run: npm run format-check

            # Step 8: Upload Test Results (optional)
            - name: Upload Test Results
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: NodeJsSecurifyTestResults
                  path: |
                      NodeJsSecurifyReport.pdf
                      NodeJsSecurifyReport.log
